server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/oauth
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root